=== Orivera04/Matlab-funciones/toolbox/mbc/mbctools/resource/namespace/mbcdatadictionary/v1/datadictionary.dtd
<!ELEMENT datadictionary (organisation, version, value*, constant*, symvalue*)>
<!ELEMENT value (name, alias*, description*, min?, max?, setpoint?, unit?)>
<!ELEMENT constant (name, alias*, description*, val, unit?)>
<!ELEMENT symvalue (name, alias*, description*, definition, min?, max?, unit?)>
<!ELEMENT organisation (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT setpoint (#PCDATA)>
<!ELEMENT val (#PCDATA)>
<!ELEMENT unit (#PCDATA)>

=== Orivera04/Matlab-funciones/toolbox/mbc/mbctraining/tutorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datadictionary PUBLIC "-//MathWorks//DTD MBCDATADICTIONARY 1.0 Alpha//EN"
"http://www.mathworks.com/namespace/mbcdatadictionary/v1/datadictionary.dtd">

<datadictionary>

<organisation>The MathWorks</organisation>
<version>1.0</version>

<value>
     <name>N</name>
     <alias>engine_speed</alias>
     <description>Engine speed (rpm)</description>
     <min>500</min>
     <max>6500</max>
     <setpoint>2500</setpoint>
</value>

<value>
     <name>L</name>
     <alias>load</alias>
     <alias>Load</alias>
     <description>Engine load (ratio)</description>
     <min>0.1</min>
     <max>1</max>
     <setpoint>0.4</setpoint>
</value>

<value>
     <name>A</name>
     <alias>afr</alias>
     <alias>AFR</alias>
     <description>Air-fuel ratio (ratio</description>
     <min>11</min>
     <max>17</max>
     <setpoint>14.35</setpoint>
</value>

<constant>
     <name>stoich</name>
     <description>Stoichiometric constant</description>
     <val>14.35</val>
</constant>

</datadictionary>

=== Orivera04/Matlab-funciones/toolbox/mbc/mbctools/resource/dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datadictionary PUBLIC "-//MathWorks//DTD MBCDATADICTIONARY 1.0 Alpha//EN"
	"http://www.mathworks.com/namespace/mbcdatadictionary/v1/datadictionary.dtd">

<datadictionary>

<organisation>The MathWorks</organisation>
<version>1.0</version>

<value>
	<name>RPM</name>
	<min>0</min>
	<max>20000</max>
	<unit>rpm</unit>
</value>
	
<symvalue>
	<name>x</name>
	<definition>y+z</definition>
	<unit>1</unit>
</symvalue>

</datadictionary>
