=== Orivera04/Matlab-funciones/toolbox/mbc/mbctools/resource/namespace/units/v1/unit.dtd
<!ELEMENT unitdatabase (organisation, version, unit*)>
<!ELEMENT unit (name, plural?, definition, displayname?, quantitytype*, symbol*, alias*)>
<!ELEMENT alias (name, plural?)>
<!ELEMENT organisation (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT plural (#PCDATA)>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT displayname (#PCDATA)>
<!ELEMENT quantitytype (#PCDATA)>
<!ELEMENT symbol (#PCDATA)>

=== Orivera04/Matlab-funciones/toolbox/mbc/mbctools/resource/mwunit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE unitdatabase PUBLIC "-//MathWorks//DTD UNITS 1.0 Alpha//EN"
	"http://www.mathworks.com/namespace/units/v1/unit.dtd">

<unitdatabase>

<organisation>The MathWorks</organisation>
<version>1.0</version>

<!-- "Units resemble sports officials: the only 
time you really pay attention to them is when 
something stupid happens." -->

<!-- SI units -->

<!-- Dimensionless (SI units) -->

<unit>
	<name>mole</name>
	<definition>mol</definition> <!-- built-in -->
	<displayname>mol</displayname>
	<quantitytype>amount of substance</quantitytype>
</unit>

<!-- Time (SI units) -->

<unit>
	<name>second</name>
	<definition>s</definition> <!-- built-in -->
	<displayname>s</displayname>
	<quantitytype>time</quantitytype>
</unit>
<unit>
	<name>minute</name>
	<definition>60 s</definition>
	<displayname>min</displayname>
	<quantitytype>time</quantitytype>
</unit>
<unit>
	<name>hour</name>
	<definition>60 min</definition>
	<displayname>hr</displayname>
	<quantitytype>time</quantitytype>
</unit>
<unit>
	<name>day</name>
	<definition>24 hr</definition>
	<quantitytype>time</quantitytype>
</unit>

<!-- Length (SI units) -->

<unit>
	<name>meter</name>
	<definition>m</definition> <!-- built-in -->
	<displayname>m</displayname>
	<quantitytype>length</quantitytype>
	<alias>
		<name>metre</name>
	</alias>
</unit>
<unit>
	<name>nautical mile</name>
	<definition>1852 m</definition>
	<displayname>nmi</displayname>
	<quantitytype>length</quantitytype>
	<alias>
		<name>nmile</name>
	</alias>
</unit>
<unit>
	<name>angstrom</name>
	<definition>1e-10 m</definition>
	<quantitytype>length</quantitytype>
</unit>

<!-- Plane angle (SI units) -->

<unit>
	<name>radian</name>
	<definition>1</definition>
	<displayname>radian</displayname>
	<quantitytype>plane angle</quantitytype>
</unit>
<unit>
	<name>arc degree</name>
	<definition>pi/180 radian</definition>
	<displayname>deg</displayname>
	<quantitytype>plane angle</quantitytype>
	<alias>
		<name>degree</name>
	</alias>
	<alias>
		<name>angular degree</name>
	</alias>
	<alias>
		<name>degree north</name>
		<plural>degrees north</plural>
	</alias>
	<alias>
		<name>degreeN</name>
		<plural>degreesN</plural>
	</alias>
	<alias>
		<name>degree N</name>
		<plural>degrees N</plural>
	</alias>
	<alias>
		<name>degree east</name>
		<plural>degrees east</plural>
	</alias>
	<alias>
		<name>degreeE</name>
		<plural>degreesE</plural>
	</alias>
	<alias>
		<name>degree E</name>
		<plural>degrees E</plural>
	</alias>
	<alias>
		<name>degree true</name>
		<plural>degrees true</plural>
	</alias>
	<alias>
		<name>degreeT</name>
		<plural>degreesT</plural>
	</alias>
	<alias>
		<name>degree T</name>
		<plural>degrees T</plural>
	</alias>
	<alias>
		<name>arcdegree</name>
	</alias>
	<alias>
		<name>arcdeg</name>
	</alias>
</unit>
<unit>
	<name>degree west</name>
	<plural>degrees west</plural>
	<definition>-1 degree_east</definition>
	<quantitytype>plane angle</quantitytype>
	<alias>
		<name>degreeW</name>
		<plural>degreesW</plural>
	</alias>
	<alias>
		<name>degree W</name>
		<plural>degrees W</plural>
	</alias>
</unit>
<unit>
	<name>arc minute</name>
	<definition>1/60 arc_degree</definition>
	<displayname>'</displayname>
	<quantitytype>plane angle</quantitytype>
	<symbol>mnt</symbol>
	<alias>
		<name>angular minute</name>
	</alias>
	<alias>
		<name>arcminute</name>
	</alias>
	<alias>
		<name>arcmin</name>
	</alias>
</unit>
<unit>
	<name>arc second</name>
	<definition>1/60 arc_minute</definition>
	<displayname>"</displayname>
	<quantitytype>plane angle</quantitytype>
	<alias>
		<name>angular second</name>
	</alias>
	<alias>
		<name>arcsecond</name>
	</alias>
	<alias>
		<name>arcsec</name>
	</alias>
</unit>

<!-- Solid angle (SI units) -->

<unit>
	<name>steradian</name>
	<definition>1</definition>
	<displayname>sr</displayname>
	<quantitytype>solid angle</quantitytype>
</unit>

<!-- Thermodynamic temperature (SI units) -->

<unit>
	<name>kelvin</name>
	<definition>kelvin</definition> <!-- built-in -->
	<displayname>K</displayname>
	<quantitytype>thermodynamic temperature</quantitytype>
	<symbol>degK</symbol>
	<symbol>deg K</symbol>
	<alias>
		<name>degree Kelvin</name>
		<plural>degrees Kelvin</plural>
	</alias>
	<alias>
		<name>degreeK</name>
		<plural>degreesK</plural>
	</alias>
	<alias>
		<name>degree K</name>
		<plural>degrees K</plural>
	</alias>
</unit>
<unit>
	<name>degree Celsius</name>
	<plural>degrees Celsius</plural>
	<definition>K @ 273.15</definition>
	<displayname>Cel</displayname>
	<quantitytype>thermodynamic temperature</quantitytype>
	<symbol>degC</symbol>
	<symbol>deg C</symbol>
	<alias>
		<name>Celsius</name>
	</alias>
	<alias>
		<name>degreeC</name>
		<plural>degreesC</plural>
	</alias>
	<alias>
		<name>degree C</name>
		<plural>degrees C</plural>
	</alias>
	<alias>
		<name>degree centigrade</name>
		<plural>degrees centigrade</plural>
	</alias>
	<alias>
		<name>centigrade</name>
	</alias>
</unit>

<!-- Temporal frequency (SI units) -->

<unit>
	<name>hertz</name>
	<definition>s-1</definition>
	<displayname>Hz</displayname>
	<quantitytype>temporal frequency</quantitytype>
</unit>

<!-- Force (SI units) -->

<unit>
	<name>newton</name>
	<definition>kg m s-2</definition>
	<displayname>N</displayname>
	<quantitytype>force</quantitytype>
</unit>

<!-- Pressure and stress (SI units) -->

<unit>
	<name>pascal</name>
	<definition>N m-2</definition>
	<displayname>Pa</displayname>
	<quantitytype>pressure</quantitytype>
	<quantitytype>stress</quantitytype>
	<symbol>pas</symbol>
</unit>
<unit>
	<name>bar</name>
	<definition>1e5 Pa</definition>
	<displayname>bar</displayname>
	<quantitytype>pressure</quantitytype>
</unit>

<!-- Energy and work (SI units) -->

<unit>
	<name>joule</name>
	<definition>N m</definition>
	<displayname>J</displayname>
	<quantitytype>energy</quantitytype>
	<quantitytype>work</quantitytype>
</unit>

<!-- Power (SI units) -->

<unit>
	<name>watt</name>
	<definition>J s-1</definition>
	<displayname>W</displayname>
	<quantitytype>power</quantitytype>
</unit>

<!-- Electrical charge (SI units) -->

<unit>
	<name>coulomb</name>
	<definition>A s</definition>
	<displayname>C</displayname>
	<quantitytype>electrical charge</quantitytype>
	<alias>
		<name>Coul</name>
	</alias>
</unit>

<!-- Electrical potential (SI units) -->

<unit>
	<name>volt</name>
	<definition>W A-1</definition>
	<displayname>V</displayname>
	<quantitytype>electrical potential</quantitytype>
</unit>

<!-- Electrical capacitance (SI units) -->

<unit>
	<name>farad</name>
	<definition>C V-1</definition>
	<displayname>F</displayname>
	<quantitytype>electrical capacitance</quantitytype>
</unit>

<!-- Electrical resistance (SI units) -->

<unit>
	<name>ohm</name>
	<definition>V A-1</definition>
	<displayname>Ohm</displayname>
	<quantitytype>electrical resistance</quantitytype>
</unit>

<!-- Electrical conductance (SI units) -->

<unit>
	<name>siemens</name>
	<plural>siemens</plural>
	<definition>ohm-1</definition>
	<displayname>S</displayname>
	<quantitytype>electrical conductance</quantitytype>
</unit>

<!-- Magnetic flux (SI units) -->

<unit>
	<name>weber</name>
	<definition>V s</definition>
	<displayname>Wb</displayname>
	<quantitytype>magnetic flux</quantitytype>
</unit>

<!-- Magnetic flux density (SI units) -->

<unit>
	<name>tesla</name>
	<definition>W m-2</definition>
	<displayname>T</displayname>
	<quantitytype>magnetic flux density</quantitytype>
</unit>

<!-- Electrical inductance (SI units) -->

<unit>
	<name>henry</name>
	<definition>W A-1</definition>
	<displayname>H</displayname>
	<quantitytype>electrical inductance</quantitytype>
</unit>

<!-- Luminous flux (SI units) -->

<unit>
	<name>lumen</name>
	<definition>cd sr</definition>
	<displayname>lm</displayname>
	<quantitytype>luminous flux</quantitytype>
</unit>

<!-- Illumination (SI units) -->

<unit>
	<name>lux</name>
	<definition>lumen m-2</definition>
	<displayname>lx</displayname>
	<quantitytype>illumination</quantitytype>
</unit>

<!-- Radioactivity (SI units) -->

<unit>
	<name>becquerel</name>
	<definition>Hz</definition>
	<displayname>Bq</displayname>
	<quantitytype>radioactivity</quantitytype>
</unit>
<unit>
	<name>curie</name>
	<definition>3.7e10 Bq</definition>
	<displayname>Ci</displayname>
	<quantitytype>radioactivity</quantitytype>
</unit>

<!-- Radiation (SI units) -->

<unit>
	<name>gray</name>
	<definition>J kg-1</definition>
	<displayname>Gy</displayname>
	<quantitytype>radiation</quantitytype>
</unit>
<unit>
	<name>rad</name>
	<definition>1e-2 Gy</definition>
	<displayname>rd</displayname>
	<quantitytype>radiation</quantitytype>
</unit>
<unit>
	<name>sievert</name>
	<definition>J kg-1</definition>
	<displayname>Sv</displayname>
	<quantitytype>radiation</quantitytype>
	<alias>
		<name>sie</name>
	</alias>
</unit>
<unit>
	<name>rem</name>
	<definition>1e-2 Sv</definition>
	<displayname>rem</displayname>
	<quantitytype>radiation</quantitytype>
</unit>

<!-- Volume (SI units) -->

<unit>
	<name>liter</name>
	<definition>1e-3 m3</definition>
	<displayname>l</displayname>
	<quantitytype>volume</quantitytype>
	<symbol>L</symbol>
	<alias>
		<name>litre</name>
	</alias>
</unit>

<!-- Mass (SI units) -->

<unit>
	<name>kilogram</name>
	<definition>kg</definition> <!-- built-in -->
	<displayname>kg</displayname>
	<quantitytype>mass</quantitytype>
</unit>
<unit>
	<name>metric ton</name>
	<definition>1000 kg</definition>
	<displayname>t</displayname>
	<quantitytype>mass</quantitytype>
	<alias>
		<name>metricton</name>
	</alias>
</unit>

<!-- Translational speed (SI units) -->

<unit>
	<name>knot</name>
	<definition>nmi hr-1</definition>
	<displayname>kt</displayname>
	<quantitytype>translational speed</quantitytype>
	<alias>
		<name>knot international</name>
	</alias>
	<alias>
		<name>international knot</name>
	</alias>
</unit>

<!-- Area (SI units) -->

<unit>
	<name>hectare</name>
	<definition>1000 m2</definition>
	<displayname>ha</displayname>
	<quantitytype>area</quantitytype>
	<alias>
		<name>har</name>
